export const COMMON_ROOMS = [
  'Kitchen',
  'Pantry',
  'Bathroom',
  'Bedroom',
  'Living Room',
  'Dining Room',
  'Laundry Room',
  'Garage',
  'Basement',
  'Attic',
  'Office',
  'Closet',
]

export const COMMON_ITEMS = [
  'Paper towels',
  'Toilet paper',
  'Tissues',
  'Trash bags',
  'Ziploc bags',
  'Aluminum foil',
  'Plastic wrap',
  'Dish soap',
  'Dishwasher pods',
  'Sponges',
  'All-purpose cleaner',
  'Glass cleaner',
  'Bleach',
  'Laundry detergent',
  'Fabric softener',
  'Dryer sheets',
  'Hand soap',
  'Shampoo',
  'Conditioner',
  'Body wash',
  'Toothpaste',
  'Deodorant',
  'Razors',
  'Cotton balls',
  'Q-tips',
  'Hand sanitizer',
  'First aid kit',
  'Batteries (AA)',
  'Batteries (AAA)',
  'Light bulbs',
  'Coffee',
  'Tea',
  'Sugar',
  'Flour',
  'Rice',
  'Pasta',
  'Cooking oil',
  'Canned soup',
  'Canned beans',
  'Cereal',
  'Peanut butter',
  'Bottled water',
  'Pet food',
]
